export default {
    products: [
        {
            _id:'1',
            name: 'Pump',
            category :'pumps',
            image: ' /images/product-1.jpg',
            price: 60,
            brand:'Hallmatro',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'2',
            name: 'Pump',
            category :'pumps',
            image: ' /images/product-2.jpg',
            price: 60,
            brand:'Hallmatro',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'3',
            name: 'Pump',
            category :'pumps',
            image: ' /images/product-3.jpg',
            price: 60,
            brand:'Hallmatro',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'4',
            name: 'Pump',
            category :'pumps',
            image: ' /images/product-4.jpg',
            price: 60,
            brand:'Hallmatro',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id:'5',
            name: 'Pump',
            category :'pumps',
            image: ' /images/product-5.jpg',
            price: 60,
            brand:'Hallmatro',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
    ],
}